version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: biblioteca_db
    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: usuario_biblioteca
      POSTGRES_PASSWORD: senha_segura@123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
